name: Terrier Maven CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk11', 'openjdk13' ]
    name: Build with Maven on ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Set openjdk
        uses: joschi/setup-jdk@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
